name: git-commit-force-release--onPush

on:
  push:
    branches:
      - master

jobs:
  git-commit-force-release--onPush:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - if: contains(github.event.head_commit.message, '[force-release]')
        run: |
          git config --global user.email "asfalte@bamdadsabbagh.com"
          git config --global user.name "asfalte"
          git commit --allow-empty -m "chore(asfalte): ðŸ”¨ git-commit-force-release--onPush"
          git push

      - if: contains(github.event.head_commit.message, '[force-release]')
        uses: peter-evans/repository-dispatch@master
        with:
          token: ${{ secrets.PAT }}
          event-type: git-commit-force-release