name: yarn-upgrade--onMondays-1000

on:
  schedule:
    - cron: '0 10 * * 1' # every monday at 1000

jobs:
  yarn-upgrade--onMondays-1000:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: '12'

      - run: yarn upgrade

      - run: |
          git config --global user.email "asfalte@bamdadsabbagh.com"
          git config --global user.name "asfalte"

      - run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "fix(asfalte): ⚙️ yarn-upgrade--onMondays-1000"

      - run: git push

