name: yarn-upgrade__0x100

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  yarn-upgrade:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: '12'

      - run: yarn upgrade

      - run: |
          git config --global user.email "asfalte@bamdadsabbagh.com"
          git config --global user.name "asfalte"

      - run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "fix: asfalte: ⚙️ yarn-upgrade__0x100"

      - run: git push

